name: movie_flutter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  syncfusion_flutter_charts: ^20.4.49
  dio: ^5.0.0
  logger: ^1.1.0
  freezed_annotation: ^2.2.0
  rxdart: ^0.27.7
  intl: ^0.18.0
  flutter_svg: ^1.1.6
  get: ^4.6.5
  hexcolor: ^3.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  assets:
    - images/
    - svgs/

